/**
 * The three things this application depends on that it does not own:
 * a database, a way to send mail, somewhere to put uploaded files.
 *
 * Each is described here as an interface and implemented in `adapters/`. The
 * rest of the codebase imports `db`, `mail` and `files`, which are thin
 * re-exports over whichever implementation `container.ts` selected — so no page
 * or handler names PostgreSQL, Resend or the local disk anywhere.
 *
 * The shapes are deliberately narrow. `Database` is not "all of node-postgres":
 * it is the four operations the application actually performs, which is what
 * makes a second implementation a day's work rather than a rewrite.
 */

/* --- database --------------------------------------------------------------- */

/** A statement inside a transaction. Mirrors what the callers destructure. */
export interface Transaction {
  query<T = Record<string, unknown>>(
    sql: string,
    params?: unknown[],
  ): Promise<{ rows: T[]; rowCount: number }>
}

export interface Database {
  query<T>(sql: string, params?: unknown[]): Promise<T[]>
  queryOne<T>(sql: string, params?: unknown[]): Promise<T | null>
  /** Rows affected. */
  execute(sql: string, params?: unknown[]): Promise<number>
  /** Commits on return, rolls back if the callback throws. */
  transaction<T>(fn: (tx: Transaction) => Promise<T>): Promise<T>
}

/* --- mail ------------------------------------------------------------------- */

export interface Attachment {
  filename: string
  content: string | Buffer
  contentType?: string
}

export interface MailMessage {
  to: string
  subject: string
  html: string
  text?: string
  attachments?: Attachment[]
}

export interface MailResult {
  ok: boolean
  id?: string
  error?: string
}

export interface Mailer {
  /**
   * Never rejects. A portal that throws because an SMTP host is unreachable
   * would fail the request that had already been carried out, so delivery
   * failures are reported in the result and logged.
   */
  send(message: MailMessage): Promise<MailResult>
}

/* --- file storage ------------------------------------------------------------ */

export interface StoredFile {
  stream: ReadableStream
  size: number
}

export interface FileStore {
  /**
   * Writes the bytes and returns the generated stored name. The name is
   * generated by the store, never taken from the upload, so no part of a
   * client-supplied filename can reach a path.
   */
  save(folder: string, originalName: string, bytes: Buffer): Promise<string>

  /**
   * Opens a stored file, or `null` if it does not exist or the identifiers are
   * not well formed. Returns a stream rather than a path, so an implementation
   * backed by object storage needs no change at the call sites.
   */
  open(folder: string, storedName: string): Promise<StoredFile | null>
}
