-- When someone was last in the portal.
--
-- A student sends in a chapter and waits. There is no way to know whether the
-- coordinator is in the portal right now — so either they write another „ați
-- văzut?”, or they wait two days for nothing. The coordinator, likewise, when
-- putting an answer off until „mai târziu”: there is no way to see whether the
-- student is still there.
--
-- A single moment is kept, not a history: it cannot be reconstructed from it
-- when somebody came in and how long they stayed, only whether they are nearby
-- right now. It is visible exclusively between the two people in a conversation
-- — already tied together by a coordination — and written coarsely: „acum”,
-- „acum câteva minute”, „astăzi”. The privacy notice says so, as everywhere
-- else in this portal.
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_seen_at timestamptz;
